server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm_demo?userUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    check-template-location: true
    suffix: .html
    prefix: /view
    mode: HTML5
    encoding: utf-8
  mvc:
    static-path-pattern: /**
  freemarker:
    suffix: .html

mybatis-plus:
  type-aliases-package: com.example.ssm_demo.entity
  mapper-locations: classpath:/mapper/*Mapper.xml

pagehelper:
  helper-dialect: mysql
  pageSizeZero: true
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
